import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  
  children,
}: {
  children: React.ReactNode
}) {
  console.log('ss')
  return (
    <html lang="en">
      <body className="mt-10 px-[10%]">{children}</body>
    </html>
  )
}
